### ISSUE TITLE
Does assertHE identify functions created inside of other functions

### ISSUE THREAD

**Issue by RobertASmith** [dark-peak-analytics/assertHE#103]
Reviewer question on this edge case, which I have definitely seen a number of times in the model.

Do we have a unit test for this?

``` 
foo1 <-
  function(x) {
    
    foo2 <- function(y, x) {
      x + y
    }
    
    foo2(x = x, y = 12)
  }


foo1(x = 10)
```

**Comment by Smit-tay** [comment]
The question appears to be:

Do we detect nested function definitions ?
If so, how are they handled ?
