### ISSUE TITLE
Extra information out of the function may be useful.

### ISSUE THREAD

**Issue by RobertASmith** [dark-peak-analytics/assertHE#21]
@Smit-tay  The function to find R functions in a script works as intended. 

https://github.com/dark-peak-analytics/assertHE/blob/8518799a02f9d773516c53bb8a86d31cb3a03a0b/R/cheers_checker.R#L225

But actually there is additional useful information here that is not being returned. For other purposes later on we may want to return the exact location in which the function is created (as well as its name). 

For example we may want later on to run this function on a large number of files and extract:
| function_name | file_path | file line number |
| ----- | ----- | ------- |
| myFoo | "./R/myFoo.R" | "L163 |

**Comment by Smit-tay** [comment]
Assuming function location would indicate the line number of the function name.

**Comment by RobertASmith** [comment]
I suppose if the whole file is parsed then it would do. Always seems to when I compare to my scripts when I parse the whole file.

If a subset of lines are parsed then I assume it would then be wrong.
